export const CANONICAL_INITIAL_DATABASE: Record<string, any[]> = {
  auth_users: [
    { id: "user-1", email: "krystelcomia@gmail.com", password: "krystel123", user_metadata: { full_name: "Krystel Comia" } },
    { id: "user-cristeta", email: "cristetalanuzaADMIN@gmail.com", password: "adminsubukincristeta2026", user_metadata: { full_name: "Cristeta R. Lanuza" } },
    { id: "user-midwife", email: "maryjanelandichoMIDWIFE@gmail.com", password: "midwifesubukinmaryjane2026", user_metadata: { full_name: "Mary Jane Landicho" } },
    { id: "user-evelyn", email: "evelynilaoBHW@gmail.com", password: "bhwsubukinevelyn2026", user_metadata: { full_name: "Evelyn T. Ilao" } },
    { id: "user-cecilia", email: "ceciliabenosaBHW@gmail.com", password: "bhwsubukincecilia2026", user_metadata: { full_name: "Cecilia G. Benosa" } },
    { id: "user-merlita", email: "merlitaalonzoBHW@gmail.com", password: "bhwsubukinmerlita2026", user_metadata: { full_name: "Merlita R. Alonzo" } },
    { id: "user-suzette", email: "suzettelopezBHW@gmail.com", password: "bhwsubukinsuzette2026", user_metadata: { full_name: "Suzette B. Lopez" } },
    { id: "user-amelita", email: "amelitasayatBHW@gmail.com", password: "bhwsubukinamelita2026", user_metadata: { full_name: "Amelita R. Sayat" } },
    { id: "user-wilma", email: "wilmatanyagBHW@gmail.com", password: "bhwsubukinwilma2026", user_metadata: { full_name: "Wilma D. Tanyag" } },
    { id: "user-nenita", email: "nenitadimaculanganBHW@gmail.com", password: "bhwsubukinnenita2026", user_metadata: { full_name: "Nenita M. Dimaculangan" } },
    { id: "user-mercy", email: "mercyabanillaBHW@gmail.com", password: "bhwsubukinmercy2026", user_metadata: { full_name: "Mercy O. Abanilla" } },
    { id: "user-renchie", email: "renchieilaoBHW@gmail.com", password: "bhwsubukinrenchie2026", user_metadata: { full_name: "Renchie V. Ilao" } },
    { id: "user-renalyn", email: "renalynlauranteBHW@gmail.com", password: "bhwsubukinrenalyn2026", user_metadata: { full_name: "Renalyn D. Laurante" } },
    { id: "user-maribel", email: "maribelabayonBNS@gmail.com", password: "bnssubukinmaribel2026", user_metadata: { full_name: "Maribel M. Abayon" } }
  ],
  user_roles: [
    { id: "role-1", user_id: "user-1", role: "bhw" },
    { id: "role-cristeta", user_id: "user-cristeta", role: "supervisor" },
    { id: "role-midwife", user_id: "user-midwife", role: "midwife" },
    { id: "role-evelyn", user_id: "user-evelyn", role: "bhw" },
    { id: "role-cecilia", user_id: "user-cecilia", role: "bhw" },
    { id: "role-merlita", user_id: "user-merlita", role: "bhw" },
    { id: "role-suzette", user_id: "user-suzette", role: "bhw" },
    { id: "role-amelita", user_id: "user-amelita", role: "bhw" },
    { id: "role-wilma", user_id: "user-wilma", role: "bhw" },
    { id: "role-nenita", user_id: "user-nenita", role: "bhw" },
    { id: "role-mercy", user_id: "user-mercy", role: "bhw" },
    { id: "role-renchie", user_id: "user-renchie", role: "bhw" },
    { id: "role-renalyn", user_id: "user-renalyn", role: "bhw" },
    { id: "role-maribel", user_id: "user-maribel", role: "bns" }
  ],
  profiles: [
    { id: "profile-1", user_id: "user-1", full_name: "Krystel Comia", username: "krystel", assigned_sitio: "Maligaya", avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80" },
    { id: "profile-cristeta", user_id: "user-cristeta", full_name: "Cristeta R. Lanuza", username: "Cristeta", assigned_sitio: "Masigla" },
    { id: "profile-midwife", user_id: "user-midwife", full_name: "Mary Jane Landicho", username: "Mary Jane", assigned_sitio: "Subukin Main" },
    { id: "profile-evelyn", user_id: "user-evelyn", full_name: "Evelyn T. Ilao", username: "Evelyn", assigned_sitio: "Manggahan 1" },
    { id: "profile-cecilia", user_id: "user-cecilia", full_name: "Cecilia G. Benosa", username: "Cecilia", assigned_sitio: "Maligaya" },
    { id: "profile-merlita", user_id: "user-merlita", full_name: "Merlita R. Alonzo", username: "Merlita", assigned_sitio: "Matahimik / Punta" },
    { id: "profile-suzette", user_id: "user-suzette", full_name: "Suzette B. Lopez", username: "Suzette", assigned_sitio: "Makalintal 1" },
    { id: "profile-amelita", user_id: "user-amelita", full_name: "Amelita R. Sayat", username: "Amelita", assigned_sitio: "Puntor" },
    { id: "profile-wilma", user_id: "user-wilma", full_name: "Wilma D. Tanyag", username: "Wilma", assigned_sitio: "Masaya" },
    { id: "profile-nenita", user_id: "user-nenita", full_name: "Nenita M. Dimaculangan", username: "Nenita", assigned_sitio: "Manggahan 2" },
    { id: "profile-mercy", user_id: "user-mercy", full_name: "Mercy O. Abanilla", username: "Mercy", assigned_sitio: "Cama" },
    { id: "profile-renchie", user_id: "user-renchie", full_name: "Renchie V. Ilao", username: "Renchie", assigned_sitio: "Makalintal 2" },
    { id: "profile-renalyn", user_id: "user-renalyn", full_name: "Renalyn D. Laurante", username: "Renalyn", assigned_sitio: "Matahimik / Burol" },
    { id: "profile-maribel", user_id: "user-maribel", full_name: "Maribel M. Abayon", username: "Maribel", assigned_sitio: "Masigla" }
  ],
  bhw_workers: [
    { id: "worker-1", name: "Krystel Comia", age: 28, address: "Subukin", gmail: "krystelcomia@gmail.com", number: "09123456789", is_online: false, user_id: "user-1", assigned_sitio: "Maligaya", avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-cristeta", name: "Cristeta R. Lanuza", age: 45, address: "Masigla", gmail: "cristetalanuzaADMIN@gmail.com", number: "0919-6980-712", is_online: false, user_id: "user-cristeta", assigned_sitio: "Masigla", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-evelyn", name: "Evelyn T. Ilao", age: 42, address: "Manggahan 1", gmail: "evelynilaoBHW@gmail.com", number: "0935-5638-247", is_online: false, user_id: "user-evelyn", assigned_sitio: "Manggahan 1", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-cecilia", name: "Cecilia G. Benosa", age: 39, address: "Maligaya", gmail: "ceciliabenosaBHW@gmail.com", number: "0921-8509-320", is_online: false, user_id: "user-cecilia", assigned_sitio: "Maligaya", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-merlita", name: "Merlita R. Alonzo", age: 48, address: "Matahimik / Punta", gmail: "merlitaalonzoBHW@gmail.com", number: "0930-9085-713", is_online: false, user_id: "user-merlita", assigned_sitio: "Matahimik / Punta", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-suzette", name: "Suzette B. Lopez", age: 36, address: "Makalintal 1", gmail: "suzettelopezBHW@gmail.com", number: "0935-2008-942", is_online: false, user_id: "user-suzette", assigned_sitio: "Makalintal 1", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-amelita", name: "Amelita R. Sayat", age: 50, address: "Puntor", gmail: "amelitasayatBHW@gmail.com", number: "0931-0232-973", is_online: false, user_id: "user-amelita", assigned_sitio: "Puntor", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-wilma", name: "Wilma D. Tanyag", age: 47, address: "Masaya", gmail: "wilmatanyagBHW@gmail.com", number: "0997-4971-138", is_online: false, user_id: "user-wilma", assigned_sitio: "Masaya", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-nenita", name: "Nenita M. Dimaculangan", age: 52, address: "Manggahan 2", gmail: "nenitadimaculanganBHW@gmail.com", number: "0985-1225-857", is_online: false, user_id: "user-nenita", assigned_sitio: "Manggahan 2", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-mercy", name: "Mercy O. Abanilla", age: 41, address: "Cama", gmail: "mercyabanillaBHW@gmail.com", number: "0949-7768-394", is_online: false, user_id: "user-mercy", assigned_sitio: "Cama", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-renchie", name: "Renchie V. Ilao", age: 34, address: "Makalintal 2", gmail: "renchieilaoBHW@gmail.com", number: "0965-6627-031", is_online: false, user_id: "user-renchie", assigned_sitio: "Makalintal 2", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-renalyn", name: "Renalyn D. Laurante", age: 37, address: "Matahimik / Burol", gmail: "renalynlauranteBHW@gmail.com", number: "0985-1086-472", is_online: false, user_id: "user-renalyn", assigned_sitio: "Matahimik / Burol", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-maribel", name: "Maribel M. Abayon", age: 44, address: "Masigla", gmail: "maribelabayonBNS@gmail.com", number: "0922-6722-134", is_online: false, user_id: "user-maribel", assigned_sitio: "Masigla", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" }
  ],
  family_data: [
    { id: "fam-1", family_number: "1", father_name: "Juan Dela Cruz", mother_name: "Maria Dela Cruz", num_males: 2, num_females: 2, num_households: 1, total_members: 4, sitio: "Cama", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "fam-2", family_number: "2", father_name: "Pedro Santos", mother_name: "Ana Santos", num_males: 1, num_females: 2, num_households: 1, total_members: 3, sitio: "Maligaya", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "fam-3", family_number: "3", father_name: "Rodrigo Reyes", mother_name: "Elena Reyes", num_males: 1, num_females: 1, num_households: 1, total_members: 2, sitio: "Masaya", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "fam-4", family_number: "4", father_name: "Antonio Ramos", mother_name: "Lourdes Ramos", num_males: 2, num_females: 1, num_households: 1, total_members: 3, sitio: "Manggahan 1", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "fam-5", family_number: "5", father_name: "Eduardo Garcia", mother_name: "Carmen Garcia", num_males: 1, num_females: 2, num_households: 1, total_members: 3, sitio: "Puntor", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "fam-6", family_number: "6", father_name: "Fernando Mendoza", mother_name: "Teresa Mendoza", num_males: 1, num_females: 1, num_households: 1, total_members: 2, sitio: "Makalintal 1", created_at: "2026-08-07T13:00:00.000Z" },
    { id: "fam-7", family_number: "7", father_name: "Manuel Bautista", mother_name: "Rosa Bautista", num_males: 2, num_females: 1, num_households: 1, total_members: 3, sitio: "Masigla", created_at: "2026-08-08T14:00:00.000Z" },
    { id: "fam-8", family_number: "8", father_name: "Leo Mandigma", mother_name: "Chichi Badillo", num_males: 3, num_females: 1, num_households: 1, total_members: 4, sitio: "Manggahan 1", created_at: "2026-08-15T08:00:00.000Z" },
    { id: "fam-9", family_number: "9", father_name: "Gabriel De Guzman", mother_name: "Jayvie Rondero", num_males: 2, num_females: 1, num_households: 1, total_members: 3, sitio: "Makalintal 2", created_at: "2026-08-16T09:00:00.000Z" }
  ],
  residents: [
    { id: "res-1", full_name: "Juan Dela Cruz", gender: "Male", age: 45, status: "Married", sitio: "Cama", birthday: "1981-05-12", family_number: "1", role_in_family: "Father", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-2", full_name: "Maria Dela Cruz", gender: "Female", age: 42, status: "Married", sitio: "Cama", birthday: "1984-08-20", family_number: "1", role_in_family: "Mother", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-3", full_name: "Carlo Dela Cruz", gender: "Male", age: 10, status: "Single", sitio: "Cama", birthday: "2016-03-15", family_number: "1", role_in_family: "Child", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-4", full_name: "Jenny Dela Cruz", gender: "Female", age: 7, status: "Single", sitio: "Cama", birthday: "2019-11-04", family_number: "1", role_in_family: "Child", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-5", full_name: "Pedro Santos", gender: "Male", age: 38, status: "Married", sitio: "Maligaya", birthday: "1988-02-14", family_number: "2", role_in_family: "Father", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-6", full_name: "Ana Santos", gender: "Female", age: 35, status: "Married", sitio: "Maligaya", birthday: "1991-09-25", family_number: "2", role_in_family: "Mother", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-7", full_name: "Baby Joy Santos", gender: "Female", age: 4, status: "Single", sitio: "Maligaya", birthday: "2022-01-10", family_number: "2", role_in_family: "Child", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-8", full_name: "Rodrigo Reyes", gender: "Male", age: 55, status: "Married", sitio: "Masaya", birthday: "1971-06-18", family_number: "3", role_in_family: "Father", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "res-9", full_name: "Elena Reyes", gender: "Female", age: 52, status: "Married", sitio: "Masaya", birthday: "1974-12-03", family_number: "3", role_in_family: "Mother", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "res-10", full_name: "Antonio Ramos", gender: "Male", age: 49, status: "Married", sitio: "Manggahan 1", birthday: "1977-04-22", family_number: "4", role_in_family: "Father", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "res-11", full_name: "Lourdes Ramos", gender: "Female", age: 46, status: "Married", sitio: "Manggahan 1", birthday: "1980-07-19", family_number: "4", role_in_family: "Mother", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "res-12", full_name: "Mark Anthony Ramos", gender: "Male", age: 12, status: "Single", sitio: "Manggahan 1", birthday: "2014-09-10", family_number: "4", role_in_family: "Child", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "res-13", full_name: "Eduardo Garcia", gender: "Male", age: 40, status: "Married", sitio: "Puntor", birthday: "1986-10-08", family_number: "5", role_in_family: "Father", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "res-14", full_name: "Carmen Garcia", gender: "Female", age: 38, status: "Married", sitio: "Puntor", birthday: "1988-03-30", family_number: "5", role_in_family: "Mother", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "res-15", full_name: "Angela Garcia", gender: "Female", age: 6, status: "Single", sitio: "Puntor", birthday: "2020-04-18", family_number: "5", role_in_family: "Child", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "res-16", full_name: "Fernando Mendoza", gender: "Male", age: 33, status: "Married", sitio: "Makalintal 1", birthday: "1993-01-14", family_number: "6", role_in_family: "Father", created_at: "2026-08-07T13:00:00.000Z" },
    { id: "res-17", full_name: "Teresa Mendoza", gender: "Female", age: 31, status: "Married", sitio: "Makalintal 1", birthday: "1995-06-20", family_number: "6", role_in_family: "Mother", created_at: "2026-08-07T13:00:00.000Z" },
    { id: "res-18", full_name: "Manuel Bautista", gender: "Male", age: 58, status: "Married", sitio: "Masigla", birthday: "1968-11-28", family_number: "7", role_in_family: "Father", created_at: "2026-08-08T14:00:00.000Z" },
    { id: "res-19", full_name: "Rosa Bautista", gender: "Female", age: 54, status: "Married", sitio: "Masigla", birthday: "1972-03-15", family_number: "7", role_in_family: "Mother", created_at: "2026-08-08T14:00:00.000Z" },
    { id: "res-20", full_name: "Joshua Garcia", gender: "Male", age: 24, status: "Single", sitio: "Masigla", birthday: "2002-08-14", family_number: "7", role_in_family: "Other", created_at: "2026-08-08T14:00:00.000Z" },
    { id: "res-21", full_name: "Leo Mandigma", gender: "Male", age: 43, status: "Married", sitio: "Manggahan 1", birthday: "1983-04-10", family_number: "8", role_in_family: "Father", created_at: "2026-08-15T08:00:00.000Z" },
    { id: "res-22", full_name: "Chichi Badillo", gender: "Female", age: 40, status: "Married", sitio: "Manggahan 1", birthday: "1986-07-22", family_number: "8", role_in_family: "Mother", created_at: "2026-08-15T08:00:00.000Z" },
    { id: "res-23", full_name: "Errol Badillo", gender: "Male", age: 19, status: "Single", sitio: "Manggahan 1", birthday: "2007-02-15", family_number: "8", role_in_family: "Child", created_at: "2026-08-15T08:00:00.000Z" },
    { id: "res-24", full_name: "John Macatangay", gender: "Male", age: 22, status: "Single", sitio: "Manggahan 1", birthday: "2004-11-03", family_number: "8", role_in_family: "Other", created_at: "2026-08-15T08:00:00.000Z" },
    { id: "res-25", full_name: "Gabriel De Guzman", gender: "Male", age: 36, status: "Married", sitio: "Makalintal 2", birthday: "1990-10-05", family_number: "9", role_in_family: "Father", created_at: "2026-08-16T09:00:00.000Z" },
    { id: "res-26", full_name: "Jayvie Rondero", gender: "Female", age: 34, status: "Married", sitio: "Makalintal 2", birthday: "1992-05-18", family_number: "9", role_in_family: "Mother", created_at: "2026-08-16T09:00:00.000Z" },
    { id: "res-27", full_name: "Kent Cueto", gender: "Male", age: 21, status: "Single", sitio: "Makalintal 2", birthday: "2005-09-29", family_number: "9", role_in_family: "Other", created_at: "2026-08-16T09:00:00.000Z" }
  ],
  consultations: [
    { id: "cons-1", resident_id: "res-1", consultation_date: "2026-08-10", consultation_cause: "Routine Health Checkup & Blood Pressure Monitoring", blood_pressure: "120/80", temperature: "36.5", weight: "68", height: "168", pulse_rate: "74", respiration_rate: "18", sitio: "Cama", created_at: "2026-08-10T09:30:00.000Z" },
    { id: "cons-2", resident_id: "res-5", consultation_date: "2026-08-14", consultation_cause: "Fever and Cough Consultation", blood_pressure: "118/76", temperature: "37.8", weight: "64", height: "165", pulse_rate: "80", respiration_rate: "20", sitio: "Maligaya", created_at: "2026-08-14T10:15:00.000Z" },
    { id: "cons-3", resident_id: "res-21", consultation_date: "2026-08-20", consultation_cause: "Hypertension Assessment & Blood Pressure Monitoring", blood_pressure: "130/85", temperature: "36.6", weight: "72", height: "170", pulse_rate: "76", respiration_rate: "18", sitio: "Manggahan 1", created_at: "2026-08-20T08:30:00.000Z" }
  ],
  philpen_health: [
    { id: "phil-1", resident_id: "res-1", family_number: "1", patient_first_name: "Juan", patient_last_name: "Dela Cruz", age: 45, gender: "Male", sitio: "Cama", blood_pressure: "120/80", fasting_blood_sugar: "95", cholesterol: "180", smoking_status: "Non-smoker", created_at: "2026-08-11T08:30:00.000Z" },
    { id: "phil-2", resident_id: "res-8", family_number: "3", patient_first_name: "Rodrigo", patient_last_name: "Reyes", age: 55, gender: "Male", sitio: "Masaya", blood_pressure: "130/85", fasting_blood_sugar: "105", cholesterol: "195", smoking_status: "Non-smoker", created_at: "2026-08-12T11:00:00.000Z" },
    { id: "phil-3", resident_id: "res-18", family_number: "7", patient_first_name: "Manuel", patient_last_name: "Bautista", age: 58, gender: "Male", sitio: "Masigla", blood_pressure: "125/80", fasting_blood_sugar: "98", cholesterol: "190", smoking_status: "Non-smoker", created_at: "2026-08-13T14:00:00.000Z" }
  ],
  dengue_prevention: [
    { id: "dengue-1", household_name: "John Macatangay", container_type: "Used Tires", has_larvae: false, action_plan: "Cover water storage tightly & practice 4S strategy", signature: "Verified by BHW", created_at: "2026-09-01T01:00:00.000Z" },
    { id: "dengue-2", household_name: "John Macatangay", container_type: "Flower Vases", has_larvae: false, action_plan: "Clean flower vases weekly", signature: "Verified by BHW", created_at: "2026-09-01T01:01:00.000Z" },
    { id: "dengue-3", household_name: "John Macatangay", container_type: "Drums / Water Tank", has_larvae: false, action_plan: "Keep drums tightly covered", signature: "Verified by BHW", created_at: "2026-09-01T01:02:00.000Z" },
    { id: "dengue-4", household_name: "Kent Cueto", container_type: "Used Tires", has_larvae: true, action_plan: "Dispose stagnant water and apply larvicide", signature: "Verified by BHW", created_at: "2026-09-01T01:03:00.000Z" },
    { id: "dengue-5", household_name: "Jayvie Rondero", container_type: "Pails / Buckets", has_larvae: false, action_plan: "Clean and invert pails when empty", signature: "Verified by BHW", created_at: "2026-09-01T01:04:00.000Z" },
    { id: "dengue-6", household_name: "Jayvie Rondero", container_type: "Roof Gutters", has_larvae: false, action_plan: "Clean roof gutters regularly", signature: "Verified by BHW", created_at: "2026-09-01T01:05:00.000Z" },
    { id: "dengue-7", household_name: "Gabriel De Guzman", container_type: "Drums / Water Tank", has_larvae: false, action_plan: "Maintain tight screen covers", signature: "Verified by BHW", created_at: "2026-09-01T01:06:00.000Z" },
    { id: "dengue-8", household_name: "Errol Badillo", container_type: "Flower Vases", has_larvae: false, action_plan: "Replace water frequently", signature: "Verified by BHW", created_at: "2026-09-01T01:07:00.000Z" },
    { id: "dengue-9", household_name: "Gabriel De Guzman", container_type: "Used Tires", has_larvae: false, action_plan: "Keep tires in covered area", signature: "Verified by BHW", created_at: "2026-09-01T01:08:00.000Z" },
    { id: "dengue-10", household_name: "Joshua Garcia", container_type: "Pails / Buckets", has_larvae: false, action_plan: "Scrub bucket walls weekly", signature: "Verified by BHW", created_at: "2026-09-01T01:09:00.000Z" },
    { id: "dengue-11", household_name: "Joshua Garcia", container_type: "Roof Gutters", has_larvae: false, action_plan: "Clear leaves from gutters", signature: "Verified by BHW", created_at: "2026-09-01T01:10:00.000Z" },
    { id: "dengue-12", household_name: "Joshua Garcia", container_type: "Drums / Water Tank", has_larvae: false, action_plan: "Keep covered with fine mesh", signature: "Verified by BHW", created_at: "2026-09-01T01:11:00.000Z" },
    { id: "dengue-13", household_name: "Leo Mandigma", container_type: "Drums / Water Tank", has_larvae: false, action_plan: "Cover water storage tightly & practice 4S strategy", signature: "Verified by BHW", created_at: "2026-09-01T01:12:00.000Z" }
  ],
  maternal_care: [],
  child_health: [],
  family_planning: [],
  user_sessions: [],
  user_activity_logs: [
    { id: "act-1", user_id: "user-1", user_name: "krystel", action: "Dengue inspection cleared", entity_type: "dengue_prevention", entity_name: "Leo Mandigma", sitio: "Manggahan 1", created_at: "2026-09-01T01:00:00.000Z" },
    { id: "act-2", user_id: "user-1", user_name: "krystel", action: "Household census profile registered", entity_type: "family_data", entity_name: "Leo Mandigma", sitio: "Manggahan 1", created_at: "2026-09-01T01:02:00.000Z" },
    { id: "act-3", user_id: "user-1", user_name: "krystel", action: "Registered in resident registry (Manggahan 1)", entity_type: "residents", entity_name: "Chichi Badillo", sitio: "Manggahan 1", created_at: "2026-09-01T01:05:00.000Z" },
    { id: "act-4", user_id: "user-1", user_name: "krystel", action: "Registered in resident registry (Subukin)", entity_type: "residents", entity_name: "Chichi", sitio: "Subukin", created_at: "2026-09-01T01:06:00.000Z" },
    { id: "act-5", user_id: "user-1", user_name: "krystel", action: "Child health & immunization check", entity_type: "child_health", entity_name: "Child", sitio: "Maligaya", created_at: "2026-09-01T01:10:00.000Z" },
    { id: "act-6", user_id: "user-1", user_name: "krystel", action: "Resident record created", entity_type: "residents", entity_name: "Joshua Garcia", sitio: "Masigla", created_at: "2026-09-01T01:15:00.000Z" }
  ]
};
