export const CANONICAL_INITIAL_DATABASE: Record<string, any[]> = {
  auth_users: [
    { id: "user-1", email: "krystelcomia@gmail.com", password: "krystel123", user_metadata: { full_name: "Krystel Comia" } },
    { id: "user-cristeta", email: "cristetalanuzaADMIN@gmail.com", password: "adminsubukincristeta2026", user_metadata: { full_name: "Cristeta R. Lanuza" } },
    { id: "user-midwife", email: "maryjanelandichoMIDWIFE@gmail.com", password: "midwifesubukinmaryjane2026", user_metadata: { full_name: "Mary Jane Landicho" } },
    { id: "user-evelyn", email: "evelynilaoBHW@gmail.com", password: "bhwsubukinevelyn2026", user_metadata: { full_name: "Evelyn T. Ilao" } },
    { id: "user-cecilia", email: "ceciliabenosaBHW@gmail.com", password: "bhwsubukincecilia2026", user_metadata: { full_name: "Cecilia G. Benosa" } },
    { id: "user-merlita", email: "merlitaalonzoBHW@gmail.com", password: "bhwsubukinmerlita2026", user_metadata: { full_name: "Merlita R. Alonzo" } },
    { id: "user-suzette", email: "suzettelopezBHW@gmail.com", password: "bhwsubukinsuzette2026", user_metadata: { full_name: "Suzette B. Lopez" } },
    { id: "user-amelita", email: "amelitasayatBHW@gmail.com", password: "bhwsubukinamelita2026", user_metadata: { full_name: "Amelita R. Sayat" } },
    { id: "user-wilma", email: "wilmatanyagBHW@gmail.com", password: "bhwsubukinwilma2026", user_metadata: { full_name: "Wilma D. Tanyag" } },
    { id: "user-nenita", email: "nenitadimaculanganBHW@gmail.com", password: "bhwsubukinnenita2026", user_metadata: { full_name: "Nenita M. Dimaculangan" } },
    { id: "user-mercy", email: "mercyabanillaBHW@gmail.com", password: "bhwsubukinmercy2026", user_metadata: { full_name: "Mercy O. Abanilla" } },
    { id: "user-renchie", email: "renchieilaoBHW@gmail.com", password: "bhwsubukinrenchie2026", user_metadata: { full_name: "Renchie V. Ilao" } },
    { id: "user-renalyn", email: "renalynlauranteBHW@gmail.com", password: "bhwsubukinrenalyn2026", user_metadata: { full_name: "Renalyn D. Laurante" } },
    { id: "user-maribel", email: "maribelabayonBNS@gmail.com", password: "bnssubukinmaribel2026", user_metadata: { full_name: "Maribel M. Abayon" } }
  ],
  user_roles: [
    { id: "role-1", user_id: "user-1", role: "bhw" },
    { id: "role-cristeta", user_id: "user-cristeta", role: "supervisor" },
    { id: "role-midwife", user_id: "user-midwife", role: "midwife" },
    { id: "role-evelyn", user_id: "user-evelyn", role: "bhw" },
    { id: "role-cecilia", user_id: "user-cecilia", role: "bhw" },
    { id: "role-merlita", user_id: "user-merlita", role: "bhw" },
    { id: "role-suzette", user_id: "user-suzette", role: "bhw" },
    { id: "role-amelita", user_id: "user-amelita", role: "bhw" },
    { id: "role-wilma", user_id: "user-wilma", role: "bhw" },
    { id: "role-nenita", user_id: "user-nenita", role: "bhw" },
    { id: "role-mercy", user_id: "user-mercy", role: "bhw" },
    { id: "role-renchie", user_id: "user-renchie", role: "bhw" },
    { id: "role-renalyn", user_id: "user-renalyn", role: "bhw" },
    { id: "role-maribel", user_id: "user-maribel", role: "bns" }
  ],
  profiles: [
    { id: "profile-1", user_id: "user-1", full_name: "Krystel Comia", username: "krystel", assigned_sitio: "Maligaya" },
    { id: "profile-cristeta", user_id: "user-cristeta", full_name: "Cristeta R. Lanuza", username: "Cristeta", assigned_sitio: "Masigla" },
    { id: "profile-midwife", user_id: "user-midwife", full_name: "Mary Jane Landicho", username: "Mary Jane", assigned_sitio: "Subukin Main" },
    { id: "profile-evelyn", user_id: "user-evelyn", full_name: "Evelyn T. Ilao", username: "Evelyn", assigned_sitio: "Manggahan 1" },
    { id: "profile-cecilia", user_id: "user-cecilia", full_name: "Cecilia G. Benosa", username: "Cecilia", assigned_sitio: "Maligaya" },
    { id: "profile-merlita", user_id: "user-merlita", full_name: "Merlita R. Alonzo", username: "Merlita", assigned_sitio: "Matahimik / Punta" },
    { id: "profile-suzette", user_id: "user-suzette", full_name: "Suzette B. Lopez", username: "Suzette", assigned_sitio: "Makalintal 1" },
    { id: "profile-amelita", user_id: "user-amelita", full_name: "Amelita R. Sayat", username: "Amelita", assigned_sitio: "Puntor" },
    { id: "profile-wilma", user_id: "user-wilma", full_name: "Wilma D. Tanyag", username: "Wilma", assigned_sitio: "Masaya" },
    { id: "profile-nenita", user_id: "user-nenita", full_name: "Nenita M. Dimaculangan", username: "Nenita", assigned_sitio: "Manggahan 2" },
    { id: "profile-mercy", user_id: "user-mercy", full_name: "Mercy O. Abanilla", username: "Mercy", assigned_sitio: "Cama" },
    { id: "profile-renchie", user_id: "user-renchie", full_name: "Renchie V. Ilao", username: "Renchie", assigned_sitio: "Makalintal 2" },
    { id: "profile-renalyn", user_id: "user-renalyn", full_name: "Renalyn D. Laurante", username: "Renalyn", assigned_sitio: "Matahimik / Burol" },
    { id: "profile-maribel", user_id: "user-maribel", full_name: "Maribel M. Abayon", username: "Maribel", assigned_sitio: "Masigla" }
  ],
  bhw_workers: [
    { id: "worker-1", name: "Krystel Comia", age: 28, address: "Subukin", gmail: "krystelcomia@gmail.com", number: "09123456789", is_online: false, user_id: "user-1", assigned_sitio: "Maligaya", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-cristeta", name: "Cristeta R. Lanuza", age: 45, address: "Masigla", gmail: "cristetalanuzaADMIN@gmail.com", number: "0919-6980-712", is_online: false, user_id: "user-cristeta", assigned_sitio: "Masigla", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-evelyn", name: "Evelyn T. Ilao", age: 42, address: "Manggahan 1", gmail: "evelynilaoBHW@gmail.com", number: "0935-5638-247", is_online: false, user_id: "user-evelyn", assigned_sitio: "Manggahan 1", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-cecilia", name: "Cecilia G. Benosa", age: 39, address: "Maligaya", gmail: "ceciliabenosaBHW@gmail.com", number: "0921-8509-320", is_online: false, user_id: "user-cecilia", assigned_sitio: "Maligaya", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-merlita", name: "Merlita R. Alonzo", age: 48, address: "Matahimik / Punta", gmail: "merlitaalonzoBHW@gmail.com", number: "0930-9085-713", is_online: false, user_id: "user-merlita", assigned_sitio: "Matahimik / Punta", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-suzette", name: "Suzette B. Lopez", age: 36, address: "Makalintal 1", gmail: "suzettelopezBHW@gmail.com", number: "0935-2008-942", is_online: false, user_id: "user-suzette", assigned_sitio: "Makalintal 1", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-amelita", name: "Amelita R. Sayat", age: 50, address: "Puntor", gmail: "amelitasayatBHW@gmail.com", number: "0931-0232-973", is_online: false, user_id: "user-amelita", assigned_sitio: "Puntor", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-wilma", name: "Wilma D. Tanyag", age: 47, address: "Masaya", gmail: "wilmatanyagBHW@gmail.com", number: "0997-4971-138", is_online: false, user_id: "user-wilma", assigned_sitio: "Masaya", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-nenita", name: "Nenita M. Dimaculangan", age: 52, address: "Manggahan 2", gmail: "nenitadimaculanganBHW@gmail.com", number: "0985-1225-857", is_online: false, user_id: "user-nenita", assigned_sitio: "Manggahan 2", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-mercy", name: "Mercy O. Abanilla", age: 41, address: "Cama", gmail: "mercyabanillaBHW@gmail.com", number: "0949-7768-394", is_online: false, user_id: "user-mercy", assigned_sitio: "Cama", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-renchie", name: "Renchie V. Ilao", age: 34, address: "Makalintal 2", gmail: "renchieilaoBHW@gmail.com", number: "0965-6627-031", is_online: false, user_id: "user-renchie", assigned_sitio: "Makalintal 2", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-renalyn", name: "Renalyn D. Laurante", age: 37, address: "Matahimik / Burol", gmail: "renalynlauranteBHW@gmail.com", number: "0985-1086-472", is_online: false, user_id: "user-renalyn", assigned_sitio: "Matahimik / Burol", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" },
    { id: "worker-maribel", name: "Maribel M. Abayon", age: 44, address: "Masigla", gmail: "maribelabayonBNS@gmail.com", number: "0922-6722-134", is_online: false, user_id: "user-maribel", assigned_sitio: "Masigla", created_at: "2026-08-01T08:00:00.000Z", updated_at: "2026-08-01T08:00:00.000Z" }
  ],
  family_data: [
    { id: "fam-1", family_number: "1", father_name: "Juan Dela Cruz", mother_name: "Maria Dela Cruz", num_males: 2, num_females: 2, num_households: 1, total_members: 4, sitio: "Cama", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "fam-2", family_number: "2", father_name: "Pedro Santos", mother_name: "Ana Santos", num_males: 1, num_females: 2, num_households: 1, total_members: 3, sitio: "Maligaya", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "fam-3", family_number: "3", father_name: "Rodrigo Reyes", mother_name: "Elena Reyes", num_males: 1, num_females: 1, num_households: 1, total_members: 2, sitio: "Masaya", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "fam-4", family_number: "4", father_name: "Antonio Ramos", mother_name: "Lourdes Ramos", num_males: 2, num_females: 1, num_households: 1, total_members: 3, sitio: "Manggahan 1", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "fam-5", family_number: "5", father_name: "Eduardo Garcia", mother_name: "Carmen Garcia", num_males: 1, num_females: 2, num_households: 1, total_members: 3, sitio: "Puntor", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "fam-6", family_number: "6", father_name: "Fernando Mendoza", mother_name: "Teresa Mendoza", num_males: 1, num_females: 1, num_households: 1, total_members: 2, sitio: "Makalintal 1", created_at: "2026-08-07T13:00:00.000Z" },
    { id: "fam-7", family_number: "7", father_name: "Manuel Bautista", mother_name: "Rosa Bautista", num_males: 2, num_females: 1, num_households: 1, total_members: 3, sitio: "Masigla", created_at: "2026-08-08T14:00:00.000Z" }
  ],
  residents: [
    { id: "res-1", full_name: "Juan Dela Cruz", gender: "Male", age: 45, status: "Married", sitio: "Cama", birthday: "1981-05-12", family_number: "1", role_in_family: "Father", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-2", full_name: "Maria Dela Cruz", gender: "Female", age: 42, status: "Married", sitio: "Cama", birthday: "1984-08-20", family_number: "1", role_in_family: "Mother", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-3", full_name: "Carlo Dela Cruz", gender: "Male", age: 10, status: "Single", sitio: "Cama", birthday: "2016-03-15", family_number: "1", role_in_family: "Child", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-4", full_name: "Jenny Dela Cruz", gender: "Female", age: 7, status: "Single", sitio: "Cama", birthday: "2019-11-04", family_number: "1", role_in_family: "Child", created_at: "2026-08-02T08:00:00.000Z" },
    { id: "res-5", full_name: "Pedro Santos", gender: "Male", age: 38, status: "Married", sitio: "Maligaya", birthday: "1988-02-14", family_number: "2", role_in_family: "Father", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-6", full_name: "Ana Santos", gender: "Female", age: 35, status: "Married", sitio: "Maligaya", birthday: "1991-09-25", family_number: "2", role_in_family: "Mother", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-7", full_name: "Baby Joy Santos", gender: "Female", age: 4, status: "Single", sitio: "Maligaya", birthday: "2022-01-10", family_number: "2", role_in_family: "Child", created_at: "2026-08-03T09:00:00.000Z" },
    { id: "res-8", full_name: "Rodrigo Reyes", gender: "Male", age: 55, status: "Married", sitio: "Masaya", birthday: "1971-06-18", family_number: "3", role_in_family: "Father", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "res-9", full_name: "Elena Reyes", gender: "Female", age: 52, status: "Married", sitio: "Masaya", birthday: "1974-12-03", family_number: "3", role_in_family: "Mother", created_at: "2026-08-04T10:00:00.000Z" },
    { id: "res-10", full_name: "Antonio Ramos", gender: "Male", age: 49, status: "Married", sitio: "Manggahan 1", birthday: "1977-04-22", family_number: "4", role_in_family: "Father", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "res-11", full_name: "Lourdes Ramos", gender: "Female", age: 46, status: "Married", sitio: "Manggahan 1", birthday: "1980-07-19", family_number: "4", role_in_family: "Mother", created_at: "2026-08-05T11:00:00.000Z" },
    { id: "res-12", full_name: "Eduardo Garcia", gender: "Male", age: 40, status: "Married", sitio: "Puntor", birthday: "1986-10-08", family_number: "5", role_in_family: "Father", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "res-13", full_name: "Carmen Garcia", gender: "Female", age: 38, status: "Married", sitio: "Puntor", birthday: "1988-03-30", family_number: "5", role_in_family: "Mother", created_at: "2026-08-06T12:00:00.000Z" },
    { id: "res-14", full_name: "Fernando Mendoza", gender: "Male", age: 33, status: "Married", sitio: "Makalintal 1", birthday: "1993-01-14", family_number: "6", role_in_family: "Father", created_at: "2026-08-07T13:00:00.000Z" },
    { id: "res-15", full_name: "Manuel Bautista", gender: "Male", age: 58, status: "Married", sitio: "Masigla", birthday: "1968-11-28", family_number: "7", role_in_family: "Father", created_at: "2026-08-08T14:00:00.000Z" }
  ],
  consultations: [
    { id: "cons-1", resident_id: "res-1", consultation_date: "2026-08-10", consultation_cause: "Routine Health Checkup & Blood Pressure Monitoring", blood_pressure: "120/80", temperature: "36.5", weight: "68", height: "168", pulse_rate: "74", respiration_rate: "18", sitio: "Cama", created_at: "2026-08-10T09:30:00.000Z" },
    { id: "cons-2", resident_id: "res-5", consultation_date: "2026-08-14", consultation_cause: "Fever and Cough Consultation", blood_pressure: "118/76", temperature: "37.8", weight: "64", height: "165", pulse_rate: "80", respiration_rate: "20", sitio: "Maligaya", created_at: "2026-08-14T10:15:00.000Z" }
  ],
  philpen_health: [
    { id: "phil-1", resident_id: "res-1", family_number: "1", patient_first_name: "Juan", patient_last_name: "Dela Cruz", age: 45, gender: "Male", sitio: "Cama", blood_pressure: "120/80", fasting_blood_sugar: "95", cholesterol: "180", smoking_status: "Non-smoker", created_at: "2026-08-11T08:30:00.000Z" },
    { id: "phil-2", resident_id: "res-8", family_number: "3", patient_first_name: "Rodrigo", patient_last_name: "Reyes", age: 55, gender: "Male", sitio: "Masaya", blood_pressure: "130/85", fasting_blood_sugar: "105", cholesterol: "195", smoking_status: "Non-smoker", created_at: "2026-08-12T11:00:00.000Z" },
    { id: "phil-3", resident_id: "res-15", family_number: "7", patient_first_name: "Manuel", patient_last_name: "Bautista", age: 58, gender: "Male", sitio: "Masigla", blood_pressure: "125/80", fasting_blood_sugar: "98", cholesterol: "190", smoking_status: "Non-smoker", created_at: "2026-08-13T14:00:00.000Z" }
  ],
  dengue_prevention: Array.from({ length: 26 }, (_, i) => ({
    id: `dengue-${i + 1}`,
    household_name: ["Juan Dela Cruz", "Pedro Santos", "Rodrigo Reyes", "Antonio Ramos", "Eduardo Garcia", "Fernando Mendoza", "Manuel Bautista"][i % 7],
    container_type: ["Drums / Water Tank", "Flower Vases", "Used Tires", "Roof Gutters", "Pails / Buckets"][i % 5],
    has_larvae: i % 6 === 0,
    action_plan: i % 6 === 0 ? "Empty and scrub container with larvicide treatment" : "Cover water storage tightly & practice 4S strategy",
    signature: "Verified by BHW",
    created_at: new Date(Date.now() - (26 - i) * 86400000).toISOString()
  })),
  maternal_care: [],
  child_health: [],
  family_planning: [],
  user_sessions: [],
  user_activity_logs: []
};
